// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-74VYIX3Tsx8ChdISoFYBbNjDgxZNypc',
    appId: '1:355327789800:web:face7ab704ff8c6b6b175d',
    messagingSenderId: '355327789800',
    projectId: 'chat-app-e3cf4',
    authDomain: 'chat-app-e3cf4.firebaseapp.com',
    storageBucket: 'chat-app-e3cf4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAv9hSUYUGInjFtAetapwBMvVsW3U_CwI',
    appId: '1:355327789800:android:587f29e861bb75f56b175d',
    messagingSenderId: '355327789800',
    projectId: 'chat-app-e3cf4',
    storageBucket: 'chat-app-e3cf4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2rr_SIoXqzOyA21XpSVWrLC9-vFFclBA',
    appId: '1:355327789800:ios:4fc2250486c90c3e6b175d',
    messagingSenderId: '355327789800',
    projectId: 'chat-app-e3cf4',
    storageBucket: 'chat-app-e3cf4.firebasestorage.app',
    androidClientId: '355327789800-4g8ku29midntguehafmfh2814bft5ei4.apps.googleusercontent.com',
    iosClientId: '355327789800-j9bfr38dkrdc80js3fecf1cmt0rmeli6.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2rr_SIoXqzOyA21XpSVWrLC9-vFFclBA',
    appId: '1:355327789800:ios:4fc2250486c90c3e6b175d',
    messagingSenderId: '355327789800',
    projectId: 'chat-app-e3cf4',
    storageBucket: 'chat-app-e3cf4.firebasestorage.app',
    androidClientId: '355327789800-4g8ku29midntguehafmfh2814bft5ei4.apps.googleusercontent.com',
    iosClientId: '355327789800-j9bfr38dkrdc80js3fecf1cmt0rmeli6.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-74VYIX3Tsx8ChdISoFYBbNjDgxZNypc',
    appId: '1:355327789800:web:c8a48b872e7737536b175d',
    messagingSenderId: '355327789800',
    projectId: 'chat-app-e3cf4',
    authDomain: 'chat-app-e3cf4.firebaseapp.com',
    storageBucket: 'chat-app-e3cf4.firebasestorage.app',
  );

}